import { nanoid } from "nanoid";
import type { ForgeFile } from "@/types/editor";

const FILE_TEMPLATES: Array<Pick<ForgeFile, "name" | "content">> = [
  {
    name: "welcome.forge",
    content: [
      "# FORGE  Welcome",
      "# Type a command and press Run, or use the terminal.",
      "#",
      "# show <topic>",
      "# inspect <project>",
      "# <entity> -> <action>",
      "# search <keyword>",
      "",
      "discover",
      "",
    ].join("\n"),
  },
  {
    name: "about.forge",
    content: [
      "# about.forge",
      "# Who is Gautam Gambhir?",
      "",
      "show about",
      "",
    ].join("\n"),
  },
  {
    name: "projects.forge",
    content: [
      "# projects.forge",
      "# 7 shipped projects",
      "",
      "show projects",
      "",
      "# Inspect a specific project:",
      "#   inspect sheriff",
      "#   inspect surfer",
      "#   inspect care-kit",
      "",
    ].join("\n"),
  },
  {
    name: "skills.forge",
    content: [
      "# skills.forge",
      "# Technical skills breakdown",
      "",
      "show skills",
      "",
    ].join("\n"),
  },
  {
    name: "experience.forge",
    content: [
      "# experience.forge",
      "# Background and experience",
      "",
      "show experience",
      "",
      "# Also worth running:",
      "#   show achievements",
      "#   show timeline",
      "",
    ].join("\n"),
  },
  {
    name: "contact.forge",
    content: [
      "# contact.forge",
      "# Get in touch",
      "",
      "show contact",
      "",
      "# Or view the resume:",
      "#   show resume",
      "",
    ].join("\n"),
  },
  {
    name: "playground.forge",
    content: [
      "# FORGE PLAYGROUND",
      "# Full scripting language - try everything here.",
      "# Press Run (Ctrl+Enter) to execute.",
      "",
      "# --- Variables ---",
      'set name    = "Gautam"',
      "set age     = 17",
      "set active  = true",
      "set score   = 98.5",
      "",
      'print("Name   : " + name)',
      'print("Age    : " + str(age))',
      'print("Active : " + str(active))',
      'print("Score  : " + str(score))',
      "",
      "# --- Strings ---",
      'set greeting = "Hello, " + name + "!"',
      "print(greeting)",
      'print("Length : " + str(len(name)))',
      'print("Upper  : " + upper(name))',
      "",
      "# --- Arrays ---",
      'set stack = ["Python", "JavaScript", "React", "Linux"]',
      'print("Stack  : " + str(stack))',
      'print("Items  : " + str(stack.length))',
      'print("First  : " + stack[0])',
      'print("Last   : " + stack.last)',
      "",
      "# --- Conditionals ---",
      "if age > 16 {",
      '  print("Status : developer")',
      "} else {",
      '  print("Status : student")',
      "}",
      "",
      "if active == true {",
      '  print("Mode   : building")',
      "}",
      "",
      "# --- Repeat loop ---",
      'print("Count:")',
      "repeat 3 {",
      '  print("  iteration " + str(i + 1))',
      "}",
      "",
      "# --- Each loop ---",
      'print("Stack items:")',
      "each lang in stack {",
      '  print("  - " + lang)',
      "}",
      "",
      "# --- Range loop ---",
      'print("Range 1-5:")',
      "each n in range(1, 6) {",
      '  print("  " + str(n))',
      "}",
      "",
      "# --- While loop ---",
      "set count = 0",
      "while count < 3 {",
      "  count = count + 1",
      '  print("While  : " + str(count))',
      "}",
      "",
      "# --- Functions ---",
      "define greet(who) {",
      '  print("Hello, " + who + "!")',
      "}",
      "",
      "define square(n) {",
      "  return n * n",
      "}",
      "",
      "define factorial(n) {",
      "  if n <= 1 {",
      "    return 1",
      "  }",
      "  return n * factorial(n - 1)",
      "}",
      "",
      'greet("world")',
      'print("4sq    : " + str(square(4)))',
      'print("5!     : " + str(factorial(5)))',
      "",
      "# --- Math builtins ---",
      'print("abs(-7)  : " + str(abs(-7)))',
      'print("sqrt(16) : " + str(sqrt(16)))',
      'print("floor pi : " + str(floor(3.14159)))',
      'print("max      : " + str(max(3, 7, 1, 9, 2)))',
      'print("min      : " + str(min(3, 7, 1, 9, 2)))',
      "",
      "# --- String builtins ---",
      'set csv   = "python,javascript,rust"',
      'set langs = split(csv, ",")',
      'print("Split  : " + str(langs))',
      'print("Joined : " + join(langs, " | "))',
      'print("Trimmed: " + trim("  hello  "))',
      "",
      "# --- Array builtins ---",
      "set arr = [1, 2, 3]",
      "set arr = push(arr, 4)",
      "set arr = push(arr, 5)",
      'print("Array  : " + str(arr))',
      'print("Length : " + str(len(arr)))',
      "",
      "# --- Type checking ---",
      'print("type num  : " + type(42))',
      'print("type str  : " + type(name))',
      'print("type arr  : " + type(stack))',
      'print("type bool : " + type(true))',
      "",
      "# --- Commands still work ---",
      "show stats",
      "",
    ].join("\n"),
  },
  {
    name: "explore.forge",
    content: [
      "# explore.forge - FORGE syntax examples",
      "",
      "# Natural commands",
      "show about",
      "show skills",
      "show projects",
      "",
      "# Inspect a project",
      "inspect sheriff",
      "",
      "# Pipe syntax (the FORGE way)",
      "about -> show",
      "projects -> count",
      "",
      "# Search",
      "search python",
      "search hacking",
      "",
      "# Discover everything",
      "discover",
      "",
    ].join("\n"),
  },
];

export const createInitialFiles = (): ForgeFile[] =>
  FILE_TEMPLATES.map((file) => ({
    id: nanoid(),
    ...file,
  }));
