// A comprehensive list of common disposable and temporary email domains
export const DISPOSABLE_DOMAINS = new Set([
  "mail.tm",
  "guerrillamail.com",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamailblock.com",
  "guerrillamail.de",
  "temp-mail.org",
  "tempmail.com",
  "10minutemail.com",
  "yopmail.com",
  "yopmail.fr",
  "yopmail.net",
  "cool.fr.nf",
  "jetable.org",
  "dispostable.com",
  "sharklasers.com",
  "mailinator.com",
  "trashmail.com",
  "mintemail.com",
  "getairmail.com",
  "burnermail.io",
  "maildrop.cc",
  "mailru.net",
  "boun.cr",
  "cachedot.net",
  "pwrby.com",
  "fakemailgenerator.com",
  "getnada.com",
  "nada.ltd",
  "duck.com", // DuckDuckGo email protection - sometimes abused but not strictly temp, but standard block lists include it. Let's keep it or focus on temp ones.
  "tempmailo.com",
  "throwawaymail.com",
  "mailnesia.com",
  "mailcatch.com",
  "discard.email",
  "dispostable.com",
  "spambog.com",
  "tempail.com",
  "moakt.com",
  "tmail.ws",
  "guerrillamail.biz",
  "guerrillamail.info",
  "guerrillamail.xyz",
  "pokemail.net",
  "grr.la",
  "shortmail.com",
  "zillamail.com",
  "inboxkitten.com",
  "mailnesia.com",
  "mailnull.com",
  "fastmail.xyz",
  "gishpuppy.com",
  "spamex.com",
  "spamgourmet.com",
  "spamhole.com",
  "trbvm.com",
  "despam.it",
  "crazymailing.com",
  "deadaddress.com",
  "tempr.email",
  "emailondeck.com",
  "anonymousemail.me",
  "temp-mail.io",
  "temp-mail.ru",
  "temp-mail.net",
  "temp-mail.com",
  "tmpmail.org",
  "tmpmail.net",
  "generator.email",
  "getmyip.cf",
  "inboxalias.com",
  "instaddr.win",
  "kapsi.fi",
  "knol.dk",
  "lortmail.dk",
  "mailbill.org",
  "mytrashmail.com",
  "one-time.email",
  "outlook.de", // not disposable
  "pissmail.com",
  "safe-mail.net",
  "silentsender.com",
  "slipry.net",
  "spambox.us",
  "spamspot.com",
  "temp-mail-generator.com",
  "temp-mail.info",
  "temp-mailbox.com",
  "tempmail.altmweb.com",
  "tempmail.co.za",
  "tempmail.de",
  "tempmail.es",
  "tempmail.fr",
  "tempmail.in",
  "tempmail.it",
  "tempmail.net",
  "tempmail.nl",
  "tempmail.pl",
  "tempmail.pt",
  "tempmail.us",
  "tempmail24.net",
  "tempmailers.com",
  "tempmailo.com",
  "tempmails.com",
  "tempmails.net",
  "temporary-email.org",
  "throwawaymail.com",
  "ulm.edu.in",
  "wegwerfemail.de",
  "yopmail.fr",
  "zapatamail.com",
  "zero-mail.com"
]);

export function isDisposableEmail(email: string): boolean {
  if (!email || !email.includes("@")) return false;
  
  const domain = email.split("@").pop()?.toLowerCase()?.trim();
  if (!domain) return false;

  // Direct check
  if (DISPOSABLE_DOMAINS.has(domain)) return true;

  // Subdomain check (e.g. sub.mail.tm should be blocked if mail.tm is blocked)
  for (const disposable of DISPOSABLE_DOMAINS) {
    if (domain.endsWith("." + disposable)) {
      return true;
    }
  }

  return false;
}
